spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: demo
    password: "demo_pass"
    url: jdbc:postgresql://zDqboaSLXivzPnxp:r4nh1SFura9ZzLY-@10.11.241.46:37627/FsVXWamGCrrkDy-V
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none

logging:
  level:
    org:
      hibernate:
        SQL: debug

server:
  port: 8180
  contextPath: /SpringIODemo

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  format_sql: true
  hbm2ddl:
    auto: none

app:
  version: vx.x-default
